export { default as AnimalAdmin } from './pages/AnimalAdmin'
export { default as AnimalMonitoring } from './pages/AnimalMonitoring'
export { default as AnimalTagging } from './pages/AnimalTagging'
export { default as Feeding } from './pages/Feeding'
export { default as Inventory } from '../inventory/Inventory'
export { default as Vitamins } from './pages/Vitamins'
