export { default as AnimalAdmin } from './AnimalAdmin'
export { default as AnimalMonitoring } from './AnimalMonitoring'
export { default as AnimalTagging } from './AnimalTagging'
export { default as Breeding } from './Breeding'
export { default as Storage } from './Storage'
export { default as Inventory } from '../inventory/Inventory'
